config/routes.rb
Rails.application.routes.draw do
	resources :problems


	#get '/problems', to: 'problems#index'
	#get '/problems/new', to: 'problems#new'
	#post '/problems', to: 'problems#create'
	#get 'problems/:id', to: 'problems#show'
	#get 'problems/:id/edit', to: 'problems#edit'
	#patch 'problems/:id', to: 'problems#update'
	#put 'problems/:id', to: 'problems#update'
	#delete 'problems/:id', to: 'problems#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	def index
		@problems= Problem.all 
	end
	def new
		@problem= Problem.new
	end
	def create
		problem= Problem.new(problem_params)
		problem.date=Time.now
		problem.status=false
		#problem.author=User.select("username")(User.find params[:id])
  		if problem.save # ummm
    		redirect_to problems_path 
  		else
    		redirect_to new_problem_path
  		end
	end
	def show
		@problem=Problem.find params[:id]
	end
	def edit
		@problem=Problem.find params[:id]
	end
	def update
		@problem=Problem.find params[:id]
		if @problem.update(problem_params)
			redirect_to problems_path
		else
			redirect_to edit_problem_path
		end
	end
	def destroy
		@problem=Problem.find params[:id]
		@problem.destroy
		redirect_to problems_path
	end
	private def problem_params
		params.require(:problem).permit(:computer_num,:detail,:status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dutywebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/problems/edit.html.erb
<h1> Edit the problem </h1>
<%= form_with(model: @problem) do |form| %>
 
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@problem.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @problem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :computer_number %><br>
    <%= form.text_field :computer_num %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :detail %>
  </p>
 
  <p>
    <%= form.label :fixed %><br>
    <%= form.check_box :status %><br>
    <!--<%= form.text_area :status %>-->
  </p>
  <p>
    <%= form.submit "Save"%>
  </p>
 
<% end %>
 
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1> Problem List </h1>
<%= link_to 'Report a new problem', new_problem_path %>
<table>
  <tr>
    <th>Date</th>
    <th>Author</th>
    <th>Computer Number</th>
    <th>Description</th>
    <th>Fixed</th>
  </tr>
  <% @problems.each do |p| %>
    <tr>
      <td><%= p.date %></td>
      <td><%= p.author %></td>
      <td><%= p.computer_num %></td>
      <td><%= p.detail %></td>
      <td><%= p.status %></td>
      <td><%= link_to 'Show', problem_path(p) %></td>
      <td><%= link_to 'Edit', edit_problem_path(p) %></td>
      <td><%= link_to 'Delete', problem_path(p), method: :delete, data:{confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/problems/new.html.erb
<h1> New Problem </h1>
<%= form_for @problem do |f| %>
  <%= f.label :computer_number %>
  <%= f.text_field :computer_num %><br>
  <%= f.label :description %>
  <%= f.text_field :detail %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/problems/show.html.erb
<p>
  <strong>Computer number:</strong>
  <%= @problem.computer_num %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @problem.detail %>
</p>
 
<p>
  <strong>Fixed:</strong>
  <%= @problem.status %>
</p>
<%= link_to 'Back', problems_path %>